### ISSUE TITLE
WinePrefixContainerPanel too wide

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1000]
When opening a `WinePrefixContainerPanel` it takes too much space. If you don't resize your Phoenicis window, this leads to the `WinePrefixContainerPanel` being larger than the space it's shown in, which leads to the hiding of the close button in the default size.

**Comment by plata** [comment]
This is not only a problem for the container details. We have the same behavior for engines. It's not so visible for apps and library because they set a max width for the details panel.

**Comment by plata** [comment]
@madoar any idea how we can solve this in a general way?

**Comment by madoar** [comment]
I don't think it's possible to solve this in a general way. 
To solve this we will need to take a look at the problematic detail views and find the components that are too large.
For the `WinePrefixContainerPanel`, I would suggest to remove one tab inside this panel a time to find the tab that is to large. If this applies to more than one tab it may be better to only show one tab each time to find out which tabs size correctly.
Afterwards we will need to change the implementation of the affected tabs to scale correctly.

**Comment by plata** [comment]
I've done that before already. It's not related to any tab. You can remove all tabs and the details view still takes the same width.
