### ISSUE TITLE
consumers in WinePrefixContainerPanel should not be automatically initialized

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1002]
The consumers inside `WinePrefixContainerPanel` are currently automatically initialized, which takes a lot of space and looks quite ugly with the automatic line breaks they contain. Here I would suggest to not automatically initialize them, or, in case we absolutely want to prevent `null` consumers, we should use `Optional<Consumer<WinePrefixContainerDTO>>`, which can then be used with `consumer.ifPresent(c -> c.accept(winePrefixContainerDTO))`.

**Comment by plata** [comment]
@madoar I really don't understand this one.

**Comment by madoar** [comment]
I'm not sure this is still relevant.
Take a look at the class `WinePrefixContainerPanel` it contains only one callback at the moment, i.e. `onDeletePrefix`. I believe we can close this.
As far as I remember the class previously contained a lot of internal Consumer variables, which were set somewhere at the top. This made the class quite large and looked ugly.
