### ISSUE TITLE
Unify some attributes from different list widget css classes

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1019]
Some css properties/attributes can be shared between the different list widgets, like the background color for the select item.
To make this easier to change and to understand we should move these attributes to a shared css class that is used by all list widgets.

For more details see #814

**Comment by plata** [comment]
Just looked at this. I don't think it makes sense to do what you propose. For example in the default theme, the icon list background is white but the details/compact lists have alternating background colors for the rows. Therefore, it is ok to have a light gray background for selected elements of the icon list but not for the other lists. As their background is gray already, you cannot really notice a gray highlight. If you select an element in the details/compact list, it is highlighted in blue (I think it's the default but anyways).

**Comment by madoar** [comment]
I think it would look better if all list widgets use the same colors for the selected and focused items.
This would make the look and feel more uniform.
This can be done the easiest way by adding a common css class for these cases.

**Comment by plata** [comment]
Then you have to use a blue highlight for the icon list as well. I think that will not look good because the contrast with the white background is quite intense.
As you seem to have a clear idea of how this should look like: Could you do a PR for it? Shouldn't be a big change to do this, right?

**Comment by madoar** [comment]
I don't think this needs to be solved now, so I would like to let it be as is currently.

**Comment by plata** [comment]
That's true. But on the other hand this is one of the issues which is polluting our backlog for a very long time already. So I really want to close it.
