### ISSUE TITLE
Local installer positioning

### ISSUE THREAD

**Issue by Ads20000** [PhoenicisOrg/POL-POM-5#1035]
The local installer button under 'Apps' should be positioned at the top-left so it is easy to find (maybe in a different background colour too, though I don't know how that would work in themes), at the moment it is placed like all other apps - alphabetically according to its name - which is not as user-friendly because it's lost in the list of apps that are automatically installed (unless you can remember it's called 'Local Installer' and find it).

**Comment by plata** [comment]
It's also in the "Custom" category. It is listed like any other installer because it is the same like any other installer.

**Comment by Ads20000** [comment]
Noted and filed #1036 
I didn't notice that button before though!

**Comment by plata** [comment]
Moreover, we cannot treat and installer in a special way. The available installers depend completely on your repository so you might not even have the local installer.

Therefore I'll close this as "won't fix".
