### ISSUE TITLE
Clicking on a category doesn't filter by category

### ISSUE THREAD

**Issue by Ads20000** [PhoenicisOrg/POL-POM-5#1036]
If I don't type anything into the search field, then click on a category, the entries are not filtered by category, nothing happens.

**Comment by plata** [comment]
Are you sure that your software is up to date? It works for me.

**Comment by madoar** [comment]
@Ads20000 In which tab are you?
The search field is currently only used in the "Apps" tab.

**Comment by Ads20000** [comment]
I'm in the Apps tab and yeah I used `git pull` only an hour ago or so

**Comment by Ads20000** [comment]
I did get some sort of conflict which I resolved with `git stash save --keep-index` so it should've downloaded the latest stuff?

**Comment by plata** [comment]
Maybe better do a clean clone and build again. Just to be sure because it should work really.

**Comment by Ads20000** [comment]
Strange, did work on a clean clone, tbf I might have forgotten to build after `pull`ing... :/
