### ISSUE TITLE
Empty Apps list

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1047]
When opening the "Apps" tab you currently see an empty apps list.

**Comment by plata** [comment]
I cannot reproduce this with a clean .Phoenicis folder.

**Comment by madoar** [comment]
No errors, just the following window:
![grafik](https://user-images.githubusercontent.com/18488086/29678765-0ba473ce-8900-11e7-984b-aa71283371ee.png)

**Comment by plata** [comment]
Now I also have it. You must have introduced it in #1039.

**Comment by plata** [comment]
Probably in the commit after I review because it was working before that.

**Comment by madoar** [comment]
This was introduced in 8c6c285c70d150a48b87206cdf9630ca1433b927

**Comment by madoar** [comment]
Or not...

**Comment by madoar** [comment]
Commit dbe8e6c24ab50218b390de27ace6ad0ad0dd1d3a already produces the empty apps list for me.

**Comment by madoar** [comment]
This is strange...

**Comment by madoar** [comment]
Ok even after `mvn clean` and `mvn test` commit dbe8e6c24ab50218b390de27ace6ad0ad0dd1d3a
still produces the empty apps list for me.

**Comment by plata** [comment]
What? How can that possibly be the case?

**Comment by madoar** [comment]
It seems to be the fuzzy search. I think 
```
FuzzySearch.partialRatio(application.getName().toLowerCase(), "") > javaFxSettingsManager.getFuzzySearchRatio())
```
may be false?

**Comment by plata** [comment]
Probably. But it worked when I implemented it. So it's somehow the combination of this and the changed filter list.

**Comment by plata** [comment]
Ok I have a fix.

**Comment by madoar** [comment]
I don't think so, because my filtered list doesn't change the content of the list widget.
