### ISSUE TITLE
text in details view unreadable

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1053]
![details text](https://user-images.githubusercontent.com/3178485/29640419-ceee5944-8856-11e7-924f-6e1a1adddc6f.png)

The text is cut off but it should be wrapped. Seems like the label is wider than the `DetailsView`.

**Comment by madoar** [comment]
It looks like the toggle buttons in the sidebar don't have the correct height too, right?
In addition the sidebar seems to be cutoff too (see All Operating System).

**Comment by plata** [comment]
The problem is that the details pane is never smaller than it's preferred width even if it does not fit in the window. I have no idea how to solve this.
