### ISSUE TITLE
Add a way to manually add a new shortcut

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1060]
Now that it's possible to update/change a shortcut, we should also add a way to manually add new shortcuts to POL/POM 5.

**Comment by plata** [comment]
I think the text is a bit misleading. It's already possible to create a new shortcut (Containers → Tools → Create shortcut). I guess what you want is that the "edit shortcut" panel is shown when you do this. Maybe we should also move the button to the library (would be more logical to have it there at least for me).
