### ISSUE TITLE
Reorganize javafx utility packages

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1073]
Currently all our javafx utility classes are contained in two packages:

- `org.phoenicis.javafx.views.common`
- `org.phoenicis.javafx.views.mainwindow.ui`

Some additional classes are also located in `org.phoenicis.javafx.views.mainwindow` like the `WaitPanel` or the `MessagePanel`.

I believe we should reorganize these packages into one package with multiple subpackages.
For example we could add a new subpackage for all our `ObservableList` classes and another one for all sidebar classes (i.e. all `Left...` classes).

**Comment by plata** [comment]
I don't think we should do that. The classes located in `org.phoenicis.javafx.views.mainwindow.ui` are specific classes for `MainWindows` whereas the classes in `org.phoenicis.javafx.views.common` are really general.

**Comment by plata** [comment]
Can we close this with #1080 and #1081 or is there anything else you want to change?

**Comment by madoar** [comment]
I would like to move our ObservableLists in a new subpackage.

**Comment by plata** [comment]
Ok. Let's track this in #1082
