### ISSUE TITLE
Class renaming 

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1074]
Some of our classes are named quite strange in my eyes.
For example the `Left...` classes, which should be named `Sidebar...` in my eyes.
In addition I think we should rename the `View...` classes to `...View`, which is more in alignment to the way the java classes are named. For example this would rename `ViewLibrary` to `LibraryView`.

**Comment by plata** [comment]
fixed in #1078 and #1077
