### ISSUE TITLE
Add parent class for our ObservableList classes

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1075]
Our 4 observable list classes have in common that they all contain the same method:

```java
    @Override
    protected void sourceChanged(ListChangeListener.Change<? extends E> c) {
        beginChange();
        while (c.next()) {
            if (c.wasPermutated()) {
                permutate(c);
            } else if (c.wasUpdated()) {
                update(c);
            } else {
                addRemove(c);
            }
        }
        endChange();
    }
```

I believe we should move this method to a common parent class for all our observable list classes.
This class should then define the abstract methods:

- permutate
- update
- addRemove

**Comment by plata** [comment]
How should this base class look like? We have:
- `AdhocList<E>`
- `ExpandedList<E, F>`
- `MappedList<E, F>`
- `PhoenicisFilteredList<E>`

`sourceChanged` is defined as `sourceChanged(ListChangeListener.Change<? extends E> c)` or `sourceChanged(ListChangeListener.Change<? extends F> c)`.
