### ISSUE TITLE
Improve the performance of PhoenicisFilteredList

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1076]
As far as I can tell we currently have no performance issues with this class, but the more scripts are added to POL/POM 5, the higher the probability to see some performance issues for this class.

The reason for this is the current implementation of:

- `int size()`
- `int getSourceIndex(int index)`, which is used in `E get(int index)` 

Both methods require the iteration through the whole list. Especially in the case of `get(index)`, this may be problematic, because you'll need a lot of iterations to get all elements inside the list if you need to get all elements contained.

For this reason I suggest to change the implementation to improve its performance.

**Comment by plata** [comment]
Any idea how this should be done?

**Comment by madoar** [comment]
Yes. Currently we're representing the filtered items via boolean list:
```java
private List<Boolean> filtered;
```

Ideally we should change this boolean list to be a list of indices, that reference to the element in the source array, that is still contained after filtering:
```java
private List<Integer> filtered;
```

If you want to get the size of the filtered list you just need to call `filtered.size()` and if you want to get the 3rd element in the filtered list you call `getSource().get(filtered.get(2))`.
The only thing that needs more work now is the insertion, update and removal, of an item.

**Comment by plata** [comment]
Can we assign you to this? I think you're the one who knows this class the best.

**Comment by madoar** [comment]
I can do this, it's just not really high on my todo list, atm.
