### ISSUE TITLE
Prevent eventual performance issues in container tab

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1097]
The current implementation of the containers tab and its filter may introduce some performance issues later on, when POL contains more than only wine engines.

The reason for this is, that every time the user changes the selected engine type new `EngineSubCategoryTab` objects are created. Each of these new objects will call `filter.addOnFilterChanged(filteredEngineVersions::trigger);`, which in turn can lead to a lot of filter `trigger()` calls when a search term has been entered.

I can think of two approaches how to solve this, either:

- add a way to remove the added filter changed trigger, when the `EngineSubCategoryTab` gets removed from the list, or
- create all available `EngineSubCategoryTab` objects, for all available `EngineCategoryTab` objects, during the instantiation of the `EnginesView`, then we would only need to switch between the tabs later on.

**Comment by plata** [comment]
I think you have some copy+paste errors in that text.
