### ISSUE TITLE
add resources repository

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1127]
We should add a new repository where we can maintain the resources which are required to develop/run Phoenicis.
For example:
- Jenkins job definitions (DSL/pipeline script)
- Wine build script (which always builds the latest Wine versions)

My goal is that it should be very easy to
- maintain your own Phoenicis (e.g. in a closed environment)
- continue the Phoenicis project (e.g. if the currently responsible people are not available anymore)

**Comment by madoar** [comment]
This sounds like a good idea. Especially because there may be people that can contribute to these things.

**Comment by qparis** [comment]
Hi,

Everything is available here: https://github.com/PlayOnLinux/WineBuild

**Comment by plata** [comment]
Ok. Wasn't aware of this. Can we move this repository to PhoenicisOrg?

**Comment by qparis** [comment]
Not really, it is widely used for POLv4. We can clone it though

**Comment by plata** [comment]
Maybe we should do that. I don't really like a clone but I think on the long run it's better than having it in the PlayOnLinux organization.

**Comment by plata** [comment]
I forked it: <https://github.com/PhoenicisOrg/WineBuild>

**Comment by plata** [comment]
@qparis can you explain how this works? E.g.: How is the list of Wine versions generated? When are the builds executed etc.?

**Comment by qparis** [comment]
The list are generated according to a list of git branches.
Custom wine patches are also listed to be compiled (see wine-patches repository). 
You need to install schroot on the build server to make it work properly.

It would be really nice to dockerize this process

**Comment by plata** [comment]
How does the build server run this? Is there a script which is executed by e.g. a cronjob? Does the build server fetch the current version of `WineBuild` from GitHub?

**Comment by qparis** [comment]
Nope, the script "winebuild" is run

**Comment by plata** [comment]
Ok. Why is there no "darwin-amd64"? And what exactly did you mean when you said that it is widely used in PoL 4? Shouldn't the software only care about the result, i.e. the .js file which lists the available versions?

**Comment by qparis** [comment]
There is a darwin-amd64 but only wine-staging can be built AFAIK
I don't understand what you mean by only care about the result

**Comment by qparis** [comment]
Which builds are missing exactly?

**Comment by plata** [comment]
In `winebuild`, I can only see `POL_Start_Winebuild "darwin-x86"`. Missing is e.g. 2.0.2, 2.0.3, 2.18 etc. Everything above 2.0.1. (stable) and 2.1 (devel and staging).

You said that we cannot move `WineBuild` because it is used in PoL4. If I understand correctly, `WineBuild` is only needed by the webserver which builds the Wine versions. So PoL4 shouldn't care where the repository is located.

Moreover, `WineBuild` seems to need a set-up environment. For example, it does a `git pull` in `$HOME/wine-patches`. How can this work without manual steps before running the script?

**Comment by qparis** [comment]
Regarding the missing build, it is generally a lack of space. Every log should be available at www.playonlinux.com/wine 

Wine patches can be pulled automatically as you said :)
Also, winebuild is hosted on two servers, this is why you cannot see darwin-x64

**Comment by plata** [comment]
Can you handle this? Maybe we can also remove some of the very old versions.

It can be pulled automatically. But to do this, `$HOME/wine-patches` has to be a git repository and I just don't see where this is cloned. I would like to have a script, which you can just run to build the Wine versions. If that's not possible, we should at least have a description how to use it.

I still don't quite understand why I don't see darwin-x64. Either, the script we have in the repository is the one which is used to build Wine then I should see darwin-x64, or it's not. In that case, we have a problem.

**Comment by qparis** [comment]
To answer all your question: winebuild has been written about 6 years ago, and the installation process is not fully automatised.
This explain pretty much why it is hard to setup

**Comment by qparis** [comment]
I can give you an access to the server where it is hosted though

**Comment by plata** [comment]
I don't really want to have access to the server. Want I want is to make sure that we have all the resources which are required to run Phoenicis available somewhere so that it doesn't die if you or any one of us is not available anymore.
To achieve this, the script doesn't have to be perfect or fully automatic. We only need a description how a Wine build server has to be setup. Especially, this includes the dependencies (e.g. schroot) and the required build environment (folders, git clones etc.).

**Comment by plata** [comment]
The resources repository has been created: https://github.com/PhoenicisOrg/resources

**Comment by qparis** [comment]
I don’t like the idea of puting all kind of resources in a git repository. We need to set explicitely the rules of what kind of files are allowed and what kind of file are not

**Comment by plata** [comment]
At least we have the repository. If you want to set some guidelines, I suggest to add them to the README or wiki there.
