### ISSUE TITLE
make scripts context aware

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1130]
Currently, a script doesn't know anything about its context when it's executed (e.g. which application it belongs to).
This leads to problems like:
- PhoenicisOrg/Scripts#361
- PhoenicisOrg/Scripts#269

It should be possible to query the `ScriptDTO`, `ApplicationDTO` etc. for a running script.

The most simple approach for this would be to inject "environment" variables into the  script execution (from `AppsController` in `setOnSelectScript`).
For example, we could inject the application ID "MafiaII" for the "Mafia II (Demo)" script as `APPLICATION_ID`. This could then be used to get the correct miniature in `WineShortcut`.

To get this working, the repository DTOs need a notion of "parent". I don't think it is possible to refer to the parent DTO object directly but it should be possible to store the ID of it. For example, `ScriptDTO` would get a new field `ApplicationId` which is filled when the repository is fetched.

I'm unsure if this is the way we should go or if there is a better solution. Therefore I've opened this issue to get your feedback before implementing something.

**Comment by madoar** [comment]
I agree, it makes many things easier if we can add some kind of `parent-child` context to the DTO objects.
The problem I see here is, that the builder pattern, which we're currently using makes this pattern really hard.
The only "easy" way I see to do this would be to change the `ApplicationDTO` constructor:

```java
    private ApplicationDTO(Builder builder) {
        if (builder.id != null) {
            if (builder.id.matches("^[a-zA-Z0-9]+$")) {
                this.id = builder.id;
            } else {
                LOGGER.warn(String.format("Application ID (%s) contains invalid characters, will remove them.",
                        builder.id));
                this.id = builder.id.replaceAll("[^a-zA-Z0-9]", "");
            }
        } else {
            this.id = null;
        }

        this.name = builder.name == null ? builder.id : builder.name;
        this.description = builder.description;
        this.icon = builder.icon;
        this.miniatures = builder.miniatures;
        this.scripts = builder.scripts.stream()
            .map(script -> script.clone())
            .map(script -> script.setApplication(this))
            .collect(Collectors.toList());
        this.resources = builder.resources;
    }
```

But I think, that this wouldn't be too intuitive location wise for later developers.

**Comment by qparis** [comment]
The idea behind this is that a script should be able to be run offline, in a standalone way (line by line).
If a script requires to be context-aware, this would break this principle except if the metadata is somehow duplicated

**Comment by plata** [comment]
@qparis I understand your point but how is your proposal to solve the issues I've linked above? In my opinion it's a bit strange that a script cannot even access the json which belongs to it. For the miniature, you would have to specify the IDs in the script.js which is really not an option because it requires that the person who writes the script understands how the Java code generates the ID.

**Comment by plata** [comment]
Btw: the script has some external dependencies already. E.g. if you do not have the translations, it will not work.

**Comment by qparis** [comment]
This is exactly the reason why scripts did not have any IDs at the begining. 
I am aware that scripts are dependencies, but it does not contradict what I have said before (can be executed line by line without any context)

**Comment by plata** [comment]
Fine. But again: how do we solve the issues if the scripts shall not have context (and what's the advantage of it)?

**Comment by qparis** [comment]
If we want the script to be aware of the context without being dependant on it, it is clear that some data needs to be duplicated and written in each script.

What I could suggest is to solve this problem the other way around : 
 * Add metadata somewhere in every script (name, category, application, icon, miniature, ...)
 * POL could then read all the scripts to generate the interface. 

It means that a repository would just be a list of script without any kind of metadata

**Comment by plata** [comment]
If we do this, the scripts become more complex. I'm not sure that the advantages of being independent (which I don't see currently), justify this. As someone writing scripts, I find it strange already that I have to specify type and category.

**Comment by qparis** [comment]
Letting the script independant makes the plateform more open and makes life easier to community to try scripts found on the forum and help communicating about improvements

**Comment by plata** [comment]
I understand this. But on the other hand: are the dependencies introduced by 3 environment variables really worse or even relevant compared to the number of Beans and functions we expose?

**Comment by qparis** [comment]
I think that the beans can be documented quite easily. They all share the same annotation and there are plenty of tools that can generate Javadoc

**Comment by plata** [comment]
So your issue is only that it's variables because they cannot be documented well? In this case, we could just have functions/Beans returning the environment. For me, a small number of environment variables would be ok (I'd just see it like WINEPREFIX or PATH).

**Comment by qparis** [comment]
It is fine to have some kind of envrionement variable inside the script, but they need to be overwrittable when the script is run manually

**Comment by plata** [comment]
Yeah sure. I never planned to forbid that. My idea was something like: inject the environment variables `TYPE_ID`, `CATEGORY_ID`, `APPLICATION_ID` and `SCRIPT_ID` from Java and use it by default in the QuickScripts. If you want to overwrite it in your script, you can just 
```Javascript
APPLICATION_ID="xyz"
```
before you call the QuickScript constructor.

**Comment by qparis** [comment]
Sounds fine

**Comment by madoar** [comment]
I'm not sure I understand why we need to manually add an application id to each script.
Can't we find the location of the application data quite easily when we take a look at its path (which we use to query the script in the first place)?

For example let's look at the `BRINK` steam script.
This script is located in `/Applications/Games/BRINK/Steam`, i.e. the path array, which we use to query it, would look like this `["Applications", "Games", "BRINK", "Steam"]`, right?
To query the application details we would simply need to remove the last element of the path array.

**Comment by plata** [comment]
The only thing I'm a bit unsure about is the ID <-> name issue. On the one hand, we cannot use the name (e.g. "TRON run/r" will just not work). On the other hand, the people who write a script cannot know anything about the ID.

**Comment by qparis** [comment]
What use cases need to access the ID within the script?

**Comment by plata** [comment]
Everything which uses `getApplication`. What we could do is to split `getApplication` in `getApplicationByName` and `getApplicationById` (for internal use only). I'm not completely aware currently if the include system works with special characters, spaces etc.

**Comment by plata** [comment]
@madoar this is exactly the point: you do not know the path.

**Comment by qparis** [comment]
The ID could also be a hash generated from the name. The name would need to be unique

**Comment by madoar** [comment]
Why don't we know the path? I mean we fetch the scripts by going through the directories, i.e. we **must** know the path at some point in time.

**Comment by plata** [comment]
That's true. But I wanted to avoid this to have containers and shortcut names which are human readable. Otherwise we would have to introduce a third concept for this.
Just remembered: The include mechanism is using IDs. If not, we would have to write something like tr("Engines") in Java.

**Comment by plata** [comment]
@madoar yes, we know it in Java. This is why I want to inject the environment variables (or path how you call it).

**Comment by madoar** [comment]
I don't know an scenario where we need to path on the javascript side.

If we really need the path or other statelike information on the javascript side, we should provide a second way, or extend our current method, to specify a script.
Maybe we can change the script definition to provide a factory method (i.e constructor) that gets called from the java side. This would allow us to provide the factory method a state object, containing information like the path, application, etc. The resulting object of the factory method we can execute on our javaside, i.e. execute the `go` method.

**Comment by plata** [comment]
We can think about that as an enhancement to my proposal later. We just have to be a bit cautious that the scripts to not get more complicated than required.
