### ISSUE TITLE
add logo for PhoenicisOrg GitHub organization

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1142]

**Comment by plata** [comment]
How about something like:
![phoenicis](https://user-images.githubusercontent.com/3973260/33393215-c0fc406e-d53e-11e7-9482-967553848d8c.png)

**Comment by madoar** [comment]
I like the second one

**Comment by plata** [comment]
@qparis how about you? I don't know what you had in mind with the name "Phoenicis" so I went for the bird. As there's also a star system called like this, I incorporated some stars in the last one.

**Comment by qparis** [comment]
Any logo is good for :) We can use the second one

**Comment by plata** [comment]
Ok. I'll create a resource repository, upload it there and assign it to the organization. I think we will have to refine it later because I'm not really an artist :P but for now it should do.

**Comment by madoar** [comment]
I believe we can start a kind of contest later on, where everyone can contribute a a logo and we choose one by vote or something.

**Comment by plata** [comment]
Yes I would like that.

**Comment by madoar** [comment]
Shouldn't we add this logo to POL/POM 5 too?

**Comment by plata** [comment]
You mean in the software?

**Comment by madoar** [comment]
Yes, the logo in the left top
