### ISSUE TITLE
Need of a filesystem-less way to set up the repository list

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/POL-POM-5#1149]
The property application.repository.configuration has been changed to application.repository.list, which is aimed to be a path to a json file.

This prevents the list of repository to be set if the filesystem is not initialized. This has two major drawbacks : 

- It prevents from using phonenicis-repository library without initializing some file system which is really restrictive for apps that are meant to be stateless (For example the website) 
- It forces to use Set.setProperty workaround when unit testing which is not thread safe when running unit tests.

This is a requirement for phoenicis-website

**Comment by plata** [comment]
Any proposals how to solve this?

**Comment by qparis** [comment]
Any reason why we changed the old pattern?

**Comment by madoar** [comment]
The initial reason for switching to json was, that simple a list of repository urls wasn't enough, therefore we needed to use another data format. 

As for why we write them in separate file: It's just easier to maintain in my eyes. 
I think we could add the json to the properties file, but I'm not sure if we want that.

About the filesystem:
I don't really understand how this is problematic. I mean travis, for example, should work with the current path, because it has a filesystem. 
In addition I don't know of a service we require, which uses our repository classes (and therefore java) and has no filesystem, therefore it's hard for me to imagine a case where this is required.
Could you please give me an example?

**Comment by plata** [comment]
@qparis we should have a section in the wiki where we collect this kind of guidelines.

Regarding the problem: we could allow a URL for `application.repository.list`. Then you could store the config somewhere on a server or in the classpath. I agree with @madoar that it might be very hard/impossible to specify the repository config in a property directly.

**Comment by qparis** [comment]
I think the json deserializer is a way to get the input we need for the module.

However, this behavior could be implemented differently (an external java class that implements an interface called RepositoryConfigurationProvider for example).

I think that the property file should contain the name of the class that will be used, and we should also provide an « official » implementation that will read a file system json file

**Comment by plata** [comment]
You mean something like <http://www.janeve.me/software-programming/dynamic-loading-using-java-reflection-and-properties>?
Would it be possible to achieve this via a Spring configuration?

**Comment by qparis** [comment]
Yeah, it is really easy actually as long as the bean is declared in the spring context, we can just something like :  

applicationContext.getBean(Class.forName(nameOfTheClass)) 

where applicationContext is autowired

**Comment by plata** [comment]
Could you give it a try (I'm really not that familiar with Spring)?

**Comment by qparis** [comment]
Sure.

**Comment by qparis** [comment]
My project is messed up. It's gonna take some time to merge it again. Basically, what I have done: 

* Remove  public List<RepositoryLocation<? extends Repository>> loadRepositoryLocations()  from RepositoryConfiguration.

**(A configuration class should never contain code)**

* Put this code apart in a bean called FilesystemJsonRepositoryLocationLoader 

`public class FilesystemJsonRepositoryLocationLoader implements RepositoryLocationLoader {
    private static final Logger LOGGER = LoggerFactory.getLogger(FilesystemJsonRepositoryLocationLoader.class);

    private final String repositoryListPath;
    private final ObjectMapper objectMapper;

    public FilesystemJsonRepositoryLocationLoader(String repositoryListPath, ObjectMapper objectMapper) {
        this.repositoryListPath = repositoryListPath;
        this.objectMapper = objectMapper;
    }

    @Override
    public List<RepositoryLocation<? extends Repository>> loadRepositoryLocations() {
        List<RepositoryLocation<? extends Repository>> result = new ArrayList<>();

        File repositoryListFile = new File(repositoryListPath);

        if (repositoryListFile.exists()) {
            try {
                result = this.objectMapper.readValue(new File(repositoryListPath),
                        TypeFactory.defaultInstance().constructParametricType(List.class, RepositoryLocation.class));
            } catch (IOException e) {
                LOGGER.error("Couldn't load repository location list", e);
            }
        } else {
            try {
                result.add(new GitRepositoryLocation.Builder()
                        .withGitRepositoryUri(new URL("https://github.com/PlayOnLinux/Scripts").toURI())
                        .withBranch("master").build());
                result.add(new GitRepositoryLocation.Builder()
                        .withGitRepositoryUri(new URL("https://github.com/PlayOnLinux/Oldwares").toURI())
                        .withBranch("master").build());
                result.add(new ClasspathRepositoryLocation("/org/phoenicis/repository"));
            } catch (URISyntaxException | MalformedURLException e) {
                LOGGER.error("Couldn't create default repository location list", e);
            }
        }

        return result;
    }

}`

Create in the same package a class called DynamicRepositoryLocationLoader

`public class DynamicRepositoryLocationLoader implements RepositoryLocationLoader {
    private final RepositoryLocationLoader delegated;

    public DynamicRepositoryLocationLoader(ApplicationContext applicationContext, String beanName) {
        this.delegated = applicationContext.getBean(beanName, RepositoryLocationLoader.class);
    }


    @Override
    public List<RepositoryLocation<? extends Repository>> loadRepositoryLocations() {
        return delegated.loadRepositoryLocations();
    }
}
`

Wire everything up in RepositoryConfiguration

I will clean this up this weekend

**Comment by qparis** [comment]
Don't understand why github won't format the code properly...

**Comment by madoar** [comment]
It looks like you've used html code tags try ```java in the line before the code block and afterwards the same without java

**Comment by plata** [comment]
I've edited your comment with @madoar's suggestion.

**Comment by madoar** [comment]
@qparis can this issue be closed with #1153?

**Comment by qparis** [comment]
Not yet, I still have a problem concerning the bean loading order ; this is preventing me from creating a RepositoryLoader from outside Phoenicis project

**Comment by plata** [comment]
Can't we place a json file somewhere on the webserver (at least until you managed to fix this)?

**Comment by qparis** [comment]
I think we should not do that

**Comment by plata** [comment]
Ok. But then: How do we proceed? Do you know a way to solve the issue or do we publish the website without listing the supported apps?

**Comment by plata** [comment]
@qparis can this be closed?
