### ISSUE TITLE
use Codacy

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1159]
We should use [Codacy](https://github.com/marketplace/codacy) to improve our quality. It can be integrated into our pull requests much better than SonarQube (which seems to be down anyways currently).
If you agree, I can try to set it up.

**Comment by madoar** [comment]
Sounds good to me.
If we decide later on that it isn't the right solution for us, we still have time to change it to something else.

**Comment by plata** [comment]
Done.
