### ISSUE TITLE
dependency management

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#1164]
Do we want to use [Gemnasium](https://github.com/gemnasium/gemnasium-maven-plugin) to manage our Maven dependencies? Gemnasium has added Java support: https://gemnasium.com/blog/announcing-java-+-maven-support/.
For multi modules we will need http://support.gemnasium.com/knowledgebase/articles/1834507-does-gemnasium-support-maven-multi-modules-project.

**Comment by plata** [comment]
I've opened a Gemnasium project so we can decide better if it's of any use for us: https://beta.gemnasium.com/projects/github.com/PhoenicisOrg/POL-POM-5

**Comment by plata** [comment]
Ok... Just saw that Gemnasium will be shut down in March, so not worth the effort (see https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/).

**Comment by plata** [comment]
We could think about [OWASP Dependency Check](https://www.owasp.org/index.php/OWASP_Dependency_Check).

**Comment by madoar** [comment]
I'm not sure what exactly OWASP Dependency Check does?

In addition I'm not sure what features the tool we want needs to have?
I can think about different possibilities:
- it should simply show us in a single table what dependencies are not up to date (kind of like david-dm: https://david-dm.org/madoar/ng2-archwizard?type=dev)

   I'm not sure such a tool exists currently, but it seems like Gemnasium went in this direction, sadly it's closing
- the dependencies that are not up to date don't really interest us, but we want a tool that automatically tries to update them to the most current version. 

   In this case I would suggest [Dependabot](https://github.com/marketplace/dependabot)

**Comment by plata** [comment]
We should just list dependencies which are not up to date. Autoupdate could possible break stuff.

**Comment by madoar** [comment]
I'm not sure the autoupdate really breaks stuff.
As far as I understand dependabot it creates a new PR for each updated dependency.
This means that if the dependency breaks stuff the tests will fail.
Then we can decide if we want to modify the code to work with the new version of the dependency or if we don't update it.

**Comment by plata** [comment]
Ok. Didn't know that. Would be fine for me. Can you try it?

**Comment by madoar** [comment]
I think I don't have the necessary rights, to set it up. I'm only able to add Dependabot to my own github account, but I think we'll need to at it to PhoenicisOrg, right?

Can you try it?

**Comment by plata** [comment]
It's installed. I think you should have the rights to configure it.

**Comment by plata** [comment]
Solved with dependabot.
