### ISSUE TITLE
Add a custom script to check for formatting

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1168]
We should add a script to the travis configuration, that checks whether the code is formatted or not.
Because travis doesn't provide such functionality out of the box, we need to provide our own script for this.

My suggestion is to write a python script, which we execute directly after the tests.
This script should first execute maven with the formatting goal. 
Afterwards it should check, whether the code has changed compared to before (using git).
If this is the case, i.e. the code has changed the script should fail.

For more information about how travis works with java projects take a look [here](https://docs.travis-ci.com/user/languages/java/).
For more information about how to modify the build take a look [here](https://docs.travis-ci.com/user/customizing-the-build/).

**Comment by plata** [comment]
We could simply check that
```
git diff --name-only | grep -v i18n/keys.pot | wc -l
```
returns 0 after the build. This could be done in the `after_success` config.

**Comment by madoar** [comment]
Do you want to give it a try?
Testing this should be quite easy. We simply need to provide a small formatting error in the same PR in which we add the command.
