### ISSUE TITLE
Test multiple java versions with travis

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#1169]
Travis allows us to test POL/POL 5 with multiple java versions from multiple vendors.
More information about this can be done, can be found [here](https://docs.travis-ci.com/user/languages/java/).

Please be aware, that as far as I remember, travis doesn't have all java versions, and some versions may not provide openjfx support.

**Comment by plata** [comment]
Which Java versions would you like to check?

**Comment by madoar** [comment]
Mainly Java 8 and 9, using both OpenJDK and OracleJDK.

**Comment by plata** [comment]
Makes sense. Can you try it (pr with the required changes in the yml)?

**Comment by madoar** [comment]
Kk

**Comment by plata** [comment]
fixed in #1172
