### ISSUE TITLE
Show wait cursor when starting app

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#478]
Especially Steam games can take some time until they start up.

**Comment by qparis** [comment]
Not sure we can determine if an app is started

**Comment by plata** [comment]
Yes. I was also thinking about this. But currently it might be confusing for the user because it is not clear whether or not PoL really did something. Maybe it would be possible to query wine if a certain exe is running.

**Comment by plata** [comment]
Closed as there is no useful way to solve this. 

While we could check if a certain exe is running, this is not really helpful. 

E.g.: The users starts a Steam game. We do not know which exe Steam will open, so we can only check for Steam itself. As Steam is opened in the background, the wait cursor will disappear immediately without any window opened. The user expects that the wait cursor will stay there until the application open (because it would work like this for other applications) and will therefore assume that something went wrong which is even worse than no wait cursor at all.

**Comment by madoar** [comment]
We could indicate that the container has been started right?
If I read the `ProcessBuilder` API correctly we get a handle to started `Process`, which we should be able to check. In this case we could change the background color or something to indicate, that the container is currently in use.

**Comment by plata** [comment]
Yes. But that wasn't the intention of this issue.
