### ISSUE TITLE
Implement LinuxTerminalOpener

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/POL-POM-5#483]

**Comment by qparis** [comment]
Just start the process with the given environment variables

**Comment by plata** [comment]
The button which shall do this is located in Containers → Tools.

**Comment by madoar** [comment]
Are there any news about this?

**Comment by plata** [comment]
Not from my side. I have to say that I'm not completely aware of the assumed use case for this. Also: How can this be combined with generic engines?

**Comment by qparis** [comment]
It is made to open any terminal. Look at the container settings tab, you will see such a feature

**Comment by plata** [comment]
@qparis I understand that point. But how/when is the user supposed to open this (e.g. instead of opening the terminal directly from his OS)?

**Comment by plata** [comment]
Apart from my concern above: Is this really essential for "alpha"?

**Comment by qparis** [comment]
Yep it is
