### ISSUE TITLE
Prevent creation of 64bit prefix and downloading 64bit wine on 32bit system

### ISSUE THREAD

**Issue by gverm** [PhoenicisOrg/POL-POM-5#548]
This could be done using the ArchitectureFetcher.

The ArchitectureFetcher is not being used anywhere right now, so if this idea is not possible or not needed, it seems obsolete to me. (Since we started using 32bit wine by default)

**Comment by plata** [comment]
This has to be done in JS. See PhoenicisOrg/Scripts#379.

**Comment by madoar** [comment]
I don't agree 100%. Ideally we also need to prevent the 64bit versions from being shown to the user, right?

**Comment by plata** [comment]
Yes. But that's still JS (the available versions are fetched in the Wine object).
