### ISSUE TITLE
Github: new Phoenicis organization?

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#579]
Do we want to transfer the repository to a new Phoenicis repository in a Phoenicis organization?

**Comment by plata** [comment]
@madoar what do you think about this? In my opinion we should do it to strengthen the new Phoenicis brand.

**Comment by madoar** [comment]
I think it's a good idea. The only problem we could face is that some people don't see the association between POL and Phoenicis. At least in the beginning this will be a problem.

**Comment by plata** [comment]
Yes, therefore the website is very important. I think it would be way worse to leave the code in the playonlinux repository first and move it later on. That would be completely confusing.

**Comment by madoar** [comment]
That's true

**Comment by madoar** [comment]
After the new github organisation https://github.com/PhoenicisOrg has been created, we only need to move the POL 5 repositories to the PhoenicisOrg right?

**Comment by plata** [comment]
I think we can move it (i.e. @qparis can move it).

**Comment by madoar** [comment]
@qparis are there any news about the new organization?

**Comment by plata** [comment]
@qparis can we do the move now (it's one of the last steps missing for alpha).

**Comment by qparis** [comment]
<img width="495" alt="capture d ecran 2017-08-15 a 12 09 29" src="https://user-images.githubusercontent.com/373645/29311554-b0826554-81b2-11e7-8f2f-6397e54f82cc.png">
I can't, don't know why

**Comment by plata** [comment]
Typo. It`s POM-POL-5

**Comment by plata** [comment]
Ok. Good. We should also do this for Scripts and Oldwares. @qparis I have the rights for Scripts but not for Oldwares so maybe it would be better if you could do it as well.

**Comment by qparis** [comment]
done

**Comment by plata** [comment]
Nice. So we can close this.

**Comment by madoar** [comment]
Just asking:
Is jenkins still working after the repository has been moved?
My guess is, that jenkins is configured for a specific organisation + repository combination right?

**Comment by qparis** [comment]
It should work but tell me if it is not the case

**Comment by plata** [comment]
Doesn't seem to work (I also thought it would). Check #977.
