### ISSUE TITLE
use JS isEngineInstalled

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#605]
Use the JS function `isEngineInstalled` instead of determining this directly in Java (e.g. ViewEngines).

**Comment by plata** [comment]
I tried it like this:
```Java
private boolean isInstalled(WineVersionDistributionDTO wineVersionDistributionDTO, WineVersionDTO wineVersionDTO, ScriptInterpreter scriptInterpreter) {
    final String[] parts = wineVersionDistributionDTO.getName().split("-");
    final String distribution = parts[0];
    final String architecture = parts[2];

    final boolean[] isInstalled = {false};
    final InteractiveScriptSession interactiveScriptSession = scriptInterpreter.createInteractiveSession();

    interactiveScriptSession.eval("include([\"Functions\", \"Engines\", \"Wine\"]);",
            ignored -> interactiveScriptSession.eval(
                    "new Wine()" +
                            ".architecture(\"" + architecture + "\")" +
                            ".distribution(\"" + distribution + "\")" +
                            ".version(\"" + wineVersionDTO.getVersion() + "\")",
                    output -> {
                        final ScriptObjectMirror wine = (ScriptObjectMirror) output;
                        isInstalled[0] = (boolean) wine.callMember("installed");
                    },
                    this::throwError),
            this::throwError
    );
    return isInstalled[0];
}
```

LocalApplicationsSource queries the repository folder several times for each check (why?) and at some point the application just freezes...

**Comment by qparis** [comment]
Because the include triggers the query and you have multiple wine versions

**Comment by plata** [comment]
If every include triggers this, we really cannot use JS for things like this. Is it necessary that the include loads the repository every time?

**Comment by qparis** [comment]
It depends on the implementation. GitApplicationsSource is cached.

Maybe we could implement a generic CachedApplicationSource

**Comment by qparis** [comment]
> Also, to be honest, I don't quite understand why engines, containers and shortcuts shall be implemented in JS. Do you have an example for a use case where someone wants to provide his own engines from a separate source?

Because it will be extremely difficult to make the difference between what should be scriptable or not. Should overrideDLL be scripted? Should verbs be scripted? In POLv4, it was not clear at all. 
Also, it is quicker to write such stuff in JS. 

> I don't see why the applications must be while Phoenicis is running at all. It should be enough to fetch them once in the beginning.

Because you don't want to have to wait the application to be loaded before being able to use it. Therefore, I propose to use a CachedApplicationSource that will only load the application source once.

**Comment by plata** [comment]
> Because it will be extremely difficult to make the difference between what should be scriptable or not. Should overrideDLL be scripted? Should verbs be scripted?

Ok, that makes sense. I would really love if you could describe the overall idea/concept of Phoenicis somewhere in the wiki. Currently, I'm often having trouble figuring out how certain things should be implemented because I don't see the whole picture. I guess this is/will be a problem also for other people who want to develop for Phoenicis. So it would be great to get this out of your head.

I created a new issue (#607) for the CachedApplicationSource topic.

**Comment by qparis** [comment]
Good!

At first, I put some static part non scripted as a Quick Win to be able to release a first version. 
But at the end, I think Phoenicis will just be a script engine + an App Store :-)

**Comment by plata** [comment]
That's exactly the kind of overall concept I'm talking about ;)

**Comment by plata** [comment]
I tried again with the CachedApplicationsSource. It's really slow.

**Comment by qparis** [comment]
The other explanation is the creation of the JS engine then

**Comment by plata** [comment]
Could you give it a try? If using JS is that slow, we need to rethink how we use it...

**Comment by madoar** [comment]
Do we have some new information regarding this, especially because the code has changed quite a lot since this issue has been opened?

**Comment by plata** [comment]
I don't think so. We probably have to try it again. Maybe if we have an `EngineUtils` class like you suggested in #983, we can query this utils instead of the engine. In this case, we would have only 1 js object in 1 js engine. I guess that should speed up things a lot.

**Comment by plata** [comment]
Superseded by #1024.
