### ISSUE TITLE
Implement ScummVM and ResidualVM engine

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/POL-POM-5#608]

**Comment by plata** [comment]
This requires a common engine interface for all engines which are implemented in JS.

**Comment by qparis** [comment]
Yes, but it will be a good target to achieve the desired design.

Also, we have to keep in mind that Wine can be required to setup these kind of games

**Comment by plata** [comment]
I just wanted to provide some more information so that someone can pick up this issue. With the title only, probably only you and me have an idea what needs to be done.

**Comment by plata** [comment]
I think this should be done in JS and therefore moved to the scripts repository.

**Comment by madoar** [comment]
I agree.

**Comment by plata** [comment]
Superseded by PhoenicisOrg/Scripts#364 and PhoenicisOrg/Scripts#365.
