### ISSUE TITLE
Check possible impact of Java 9

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#618]

**Comment by madoar** [comment]
Depending on how far the Java dev team gets when they release Java 9, it's possible that we can use ES6 class definitions in Java 9, which would make some things a lot easier to read.

**Comment by plata** [comment]
First of all we have to be sure that Java 9 does not break anything.

**Comment by plata** [comment]
Java 9 is tested with Travis since #1172
