### ISSUE TITLE
Implement generic engine handling

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#620]
I'm thinking about the following: In the scripts we have an engines folder containing several types of engines (Wine, ScummVM...). The engines tab would just loop over all engines similar to how the apps tab gets all categories. Every one of those engines implements `fetchAvailableVersions`. The result of this is not stored in an engine specific DTO but in a general EngineDTO. The EngineDTO contains certain fields like category, name etc., which apply to all engines. Additionally, there is a engineData field with information specific to a certain engine type (in JSON). For the installation and deletion, every engine must implement `install` and `delete`. Those functions receive an EngineDTO as parameter.

### Container tab
We have to move all of this to JS. Without thinking a lot about it, we could do something like:
* Have a generic function `getEngineTools` in the JS engine which returns a list of function names and tool button icons. If you click a button, we call the provided function from Java.
* "Display" and "Input" are moved to a generic "Settings" tab (so we have "Information", "Settings", "Tools").
* Settings must be provided by JS, e.g. `getSettings` function which returns a list of `EngineSetting`. `EngineSetting` has a name, type (string, number, choice) etc.

To avoid having to implement a lot of functions for a new engine, we can have all of this optional. If you don't want to provide any tool, you do not have to implement anything. To do this, we derive all engine types from a base class `Engine` which e.g. returns an empty list for `getEngineTools`.

**Comment by madoar** [comment]
I think #702 should be included here too.

**Comment by madoar** [comment]
@qparis what do you think about this?

**Comment by qparis** [comment]
I think we should think about the way it is done, but I'd like to release a alpha version first

**Comment by plata** [comment]
I agree with @qparis. This is something internal which should not be noticed by the users (unless you provide your own engines of course, but that shouldn't affect alpha).

**Comment by madoar** [comment]
The problem currently is, that we have quite a few issues which target the container tab and the engines (#833 #834 #702 #625). If we do these issues, or at least the issues marked for the alpha release, first and then this issue (#620), we'll need to do a lot of things two times, the first time when we work on the previous issues and then again when we move the features to javascript as part of this issue.

**Comment by plata** [comment]
You are right (didn't see that #833 and #834 are assigned to alpha).

**Comment by madoar** [comment]
I think it would be a good idea to start the whole topic by moving wine engine specific functions from java (the POL 5 repository) to javascript (the Scripts repository). 
When doing this we can also add functions for #833 and #834 at the same time in javascript.
In the next step we can then replace our current container details view gui by a new one that is more generic.
What do you think?

**Comment by plata** [comment]
Yes, that's probably the best approach. For #833 and #834 it should be enough to have
* createShortcut
* runInsideContainer (which can be renamed from `runInsidePrefix`)

**Comment by madoar** [comment]
Do you want to give this a go?
I think you know better what needs to be done to do this in a good way than me.

**Comment by plata** [comment]
Just had a look at it. We can implement #833 and #834 with the current setup and do the generic engines later.

**Comment by plata** [comment]
Superseded by #1024.
