### ISSUE TITLE
Change engine for existing container

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#625]
Allow to change the engine for an existing container (i.e. write new values to `phoenicis.cfg`). 
Currently, the container view is not really prepared to do this as it only shows information from a DTO. Probably there should be a WinePrefixContainerController which can populate a ComboBox in the WinePrefixContainerPanel with the versions obtained from WineVersionManager.

**Comment by feanor12** [comment]
As a workaround I  added a second installer to the game folder which just installs the wine version I want
feanor12/Scripts@b634719

**Comment by madoar** [comment]
@plata I've just tried to work on this issue, but couldn't find the class `WineVersionManager`. Can you tell me where this class is located?
In addition is there an easy way implemented, to access (read and write) the file `phoenicis.cfg`?

**Comment by plata** [comment]
The `Wine...` has been renamed to `Engine...` by now (Wine is a special Engine). You can find the related classes in `phoenicis-engines`. The `phoenicis.cfg` is handled by `Functions/Engines/Wine/script.js`. The general idea for the engines is that you define your engines (e.g. Wine) in JS and plug them into the GUI in a generic way.

**Comment by madoar** [comment]
Ok, I've got a first working version, that can at least show me a list of all available engine versions in a `ComboCox`.

I have multiple "problems" with my approach and the current Engines architecture:

- On big problem is, that my solution looks really ugly and kind of glued together. This is founded in the existing method structure, where method a calls b, which calls c, which calls d and so on until finally method `drawInformationTab` in WinePrefixContainerPanel is called.
- Another problem is that the engines part is uncommented. I must confess, I don't really understand what the different classes in the project `phoenicis-engines` mean and contain and how they belong together. I know for example that, that an `EngineCategoryDTO` contains multiple `EngineSubCategoryDTO`s, which in turn contain multiple `EngineVersionDTO`s, but what is the meaning of each of these classes?
- Another problem is the filtering of the engine versions, which fit to the selected container. Currently in my simple version, I show all engine versions. But I think we should only show versions, that compatible with the selected container. Let's say for example we have a container with a Wine 2.0 engine version. In this case I think we should only show wine versions.
- One missing part in my implementation is the saving of the engine version after it has been changed in the ComboBox. Here I'm missing some code that enables us to easily write to the container configuration.

**Comment by madoar** [comment]
I've just created a new PR with my current code. See #698.

**Comment by plata** [comment]
Let me try to explain `phoenicis-engines` a bit:
In general, this module manages the engines which are implemented in JS. There is a hierarchical structure to order the engines. On top level, the category (`EngineCategoryDTO`) is e.g. Wine. This is then divided into several subcategories (`EngineSubCategoryDTO`) e.g. x86-staging, amd64-upstream. Finally, the version (`EngineVersionDTO`) gives you the special engine version e.g. Wine 2.0 x86-upstream.
I hope this makes things more clear for you. You're of course welcome to enhance the Javadoc accordingly.

To save the container configuration: We have to think about whether or not this can be done in a general way for all containers. If not, it must be implemented through a general interface in JS.

**Comment by madoar** [comment]
Some other things I think we should solve/improve to make working with engines easier:
One thing I think we need to make working with the engines much easier, is an upstream relationship between the different levels.
Currently it's only possible to get the subcategories of a category but not the other way round, you can't query the category belonging to a subcategory in an easy way. The same is true for the subcategories and the engine versions, where you can get the engine versions of a subcategory but not the subcategory belonging to an engine version.

I addition it's currently quite hard to get an `EngineVersionDTO`, `EngineSubCategoryDTO` and `EngineCategoryDTO` object that belong to a `WinePrefixContainerDTO` object.
I think the `WinePrefixContainerDTO` class should have getter methods for these objects.

**Comment by plata** [comment]
The `WinePrefixContainerDTO` has `architecture`, `distribution` and `version`. Probably it would make more sense if the `ContainerDTO` had `engineCategory`, `engineSubCategory` and `engineVersion`. However, I don't think it should have the DTOs directly (how would you parse that from json?).

**Comment by madoar** [comment]
Currently it's a lot of work to find the correct `EngineVersionDTO`, `EngineSubCategoryDTO` and `EngineCategoryDTO` objects for a `ContainerDTO`, therefore I think it would make a lot of sense to make it easier to find the correct objects.
I'm not sure we need to parse it directly from json. Why don't we do a bit preprocessing first on the `ContainerDTO` to find/insert the correct `EngineVersionDTO`, `EngineSubCategoryDTO` and `EngineCategoryDTO` objects?

**Comment by plata** [comment]
I know but I don't believe that's a good idea. The DTO should be a plain data container only and it would mix the engine and container modules. On the other hand we must find a way to connect engines and containers somehow. Pretty sure @qparis has a plan for this in mind already.

**Comment by madoar** [comment]
As a side note:
We have a similar problem with `CategoryDTO` and `ApplicationDTO`s too. You can query a category for its applications, but not the other way round. In more than one situation I've wished for a `getCategory` method in the `ApplicationDTO` class, to query the category object.

**Comment by plata** [comment]
I know. I had the same issues already as well.

**Comment by plata** [comment]
Superseeded by #992.
