### ISSUE TITLE
Implement generic engine changeVersion

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#702]
It could be implemented similarly to engine install/delete, i.e. 
- add `ChangeEngineVersionUi` (see `EngineProgressUi`)
- implement `changeVersion` in JS
- call `changeVersion` of correct engine depending on container from Java

see #698

**Comment by madoar** [comment]
This should be implemented relatively soon, because we currently only have a half functional engines list in the container view, which is for one slow during the initialization and doesn't do anything afterwards.

**Comment by plata** [comment]
Superseded by #1024.
