### ISSUE TITLE
Incorrect title of window in GNOME menu

### ISSUE THREAD

**Issue by pyroxar** [PhoenicisOrg/POL-POM-5#713]
I use ubuntu GNOME 17.04 with GNOME 3.24.
In PlayOnLinux 4 and PlayOnLinux 5 title in GNOME menu is incorrect. Title of window is correct "PlayOnLinux" but in gnome menu is not.
See on screenshot.
![zrzut ekranu z 2017-04-16 22-49-31](https://cloud.githubusercontent.com/assets/23406555/25074275/c36d3fdc-22f7-11e7-9c57-d7d5e88219ab.png)

**Comment by plata** [comment]
Cannot test, but maybe it's [this](https://stackoverflow.com/questions/21111481/javafx-application-name)?

**Comment by madoar** [comment]
I think we should also adjust the title to contain spaces (e.g. `Play on Linux`) and maybe to contain `Phoenicis` too.
What do you think @plata, @qparis?

**Comment by plata** [comment]
It should be "Phoenicis PlayOnLinux" (it is correct without spaces as you can see e.g. on the [homepage](https://www.playonlinux.com/en/)).
