### ISSUE TITLE
Adjust the ShortcutDTO creation method to correctly work with URIs

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#780]
After merging #773 the creation of a `ShortcutDTO` is as followed:
When a `ShortcutDTO` is created, it receives the `URI` objects from the corresponding `ApplicationDTO` object. Only after a restart of POL 5 the `URI` will be corrected to link to a copy of the icon/miniature, which belong to the shortcut, instead of the icon/miniature belonging to the `ApplicationDTO`.

We should adjust the behavior, with the goal, that the shortcut creation method takes a `ScriptDTO` and an `ApplicationDTO`. During the creation method the needed icons/miniatures should be copied for the new shortcut, and the new `ShortcutDTO` should be created.

**Comment by plata** [comment]
Shouldn't the call `libraryManager.refresh();` in `ShortcutManager#createShortcut` ensure this?

**Comment by madoar** [comment]
You're right.
Still I think, we should change the parameters that are passed to `ShortcutManager#createShortcut`, because we're basically using a `ShortcutDTO` object to create another `ShortcutDTO` object, which we're then using. 

I don't like this approach because I think it's unintuitive. I think we should change `ShortcutManager#createShortcut` to accept a an `ApplicationDTO` and a `ScriptDTO` object, for which a shortcut should be created, because these two objects are the sources for all fields relevant for the shortcut, right?

**Comment by plata** [comment]
I don't know. For me `createShortcut` means: create all files belonging to a shortcut based on a given object. If we change it to `ApplicationDTO` and `ScriptDTO`, we might find out at some point in time that we need additional information. Then we would have to pass `ApplicationDTO` and `ScriptDTO` and the additional information. If we pass a `ShortcutDTO`, we only have to enhance this object. Moreover, the current solution seems to be working so I don't really see a reason to change it.

**Comment by madoar** [comment]
The current solution is just not easy to understand. If this function should be enhanced someday or modified I'm not sure if this can be easily done then.

**Comment by plata** [comment]
That's true. But I doubt that it would be better to use `ApplicationDTO` and `ScriptDTO`.

**Comment by madoar** [comment]
I think we can close this, but we should still have this issue in our backlog, and decide again at a later time if this can be done in a better, easier to understand way. Maybe after we're changed the engine structure.
