### ISSUE TITLE
Refactor AppPanel

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#818]
Currently the class `AppPanel`, which is opened when a user selects an application in the "Apps" tab, needs to be refactored:

- [ ] the class shouldn't add a css class to itself directly, because this affects the look and feel of the header of the details view, which contains the title and close button
- [X] the used `WebView` needs to update its css automatically, whenever the theme is switched (see #747 for details and how to possibly solve this)
- [x] the tooltip, which should be shown when the `viewScriptSource` checkbox in the settings has been enabled, isn't shown currently
- [X] when having multiple repositories with a script for the same application the images of both scripts are shown in the `AppPanel`, even if both images have the exact same content

**Comment by madoar** [comment]
Fell free to split it up when working on this :)

**Comment by plata** [comment]
1. still valid?
2. should be fixed by #823 
3. to do
4. fixed by #855

Correct?

@madoar do you see why I didn't like everything in one issue? Now we have this partly fixed and it's difficult to track when it can be closed/what still has to be done.

**Comment by plata** [comment]
Opened #953 to track the tooltip issue.

**Comment by plata** [comment]
I would also like to track the first point in a separate issue but I don't quite understand it/what has to be changed. @madoar could you help me there?

**Comment by madoar** [comment]
As far as I remember the problem is that `AppPanel` sets an **additional** css class to itself.
The first, and main, css class is set in the constructor of `DetailsView` (which also sets 2 classes which is one to much in my opinion).
These multiple css classes are dangerous because they set the same style properties with different values (e.g. paddings, etc.). 
In my opinion all details views should use the same css class for some basic things like paddings.

**Comment by plata** [comment]
I'm not sure we can use the paddings in every details view. After all, they might contain completely different data/controls.

**Comment by madoar** [comment]
We're not only talking about the data/controls set by the details view implementation, but also about paddings that react with with close button and the header title for the details view.
If you for example compare the details view of the "Apps" tab and the "Library" tab with each other, you'll discover, that the header row has different paddings for both tabs.
This is rooted in the additional css class set by `AppPanel`.

**Comment by plata** [comment]
Would you mind implementing this? (I guess you know best what should be handled in the CSS for the details panel and what in the CSS for the special implementation).

**Comment by madoar** [comment]
The question is how do we want to solve this?
Do we want to have a single css class we add to every details view implementation?
Or do we want to add a custom css class to every details view implementation?

**Comment by plata** [comment]
I think we should have a CSS class for the details view which handles the basic layout (close button etc). And then one CSS class for every details view for the specific controls.

**Comment by madoar** [comment]
Hmm, how do we prevent both css classes from interfering with each other?

**Comment by plata** [comment]
We cannot. But I'm not sure it makes sense to handle everything in the CSS for the details view because you just cannot know what it contains.
The only thing we could do is put the content in a separate panel and apply the CSS for every details view only to that panel.

**Comment by plata** [comment]
first task is handled in #1006
