### ISSUE TITLE
Refactor EnginePanel

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#820]
Currently the class `EnginePanel`, which is opened when a user selects an engine in the "Engines" tab, needs to be refactored:

- [x] the class shouldn't add a css class to itself directly, because this affects the look and feel of the header of the details view, which contains the title and close button
- [x] inside `EnginePanel` some javafx components use `setSpacing()`, `setPrefHeight` and other similar methods, this should be moved to the less theme files, to enable the components to scale correctly

**Comment by plata** [comment]
@madoar I don't understand "the class shouldn't add a css class to itself directly". Can you explain this a bit more (e.g. which lines in the code)? Also: Can we access the different Region, HBox etc. from Less directly or do we have to create a class for each of those?

**Comment by plata** [comment]
first task is handled in #1006

**Comment by plata** [comment]
second task has been fixed in #998
