### ISSUE TITLE
[Feature] Check that wine is running in a compatible filesystem

### ISSUE THREAD

**Issue by qparis** [PhoenicisOrg/POL-POM-5#835]

**Comment by madoar** [comment]
What do you mean with `compatible filesystem`? When should this be checked? During the installation? When starting an application inside a container?

**Comment by qparis** [comment]
Any filesystem supported by wine 

"2.1.1 Does Wine run on all Unix filesystems?

Mostly. Wine is written to be filesystem independent so MS Windows applications should work on virtually any full-featured UNIX filesystem. The key exception is that not all filesystems / drivers support every feature of fat32 or NTFS. One example is that the ntfsv3 drivers do not support shared-write mmap, a feature that cannot be emulated and is used by applications such as Steam.

One other point is that Wine is a weird application in ways and some programs work better on case-insensitive filesystems (see Case Insensitive Filenames for more details). "

We should check this everytime wine is launched

**Comment by plata** [comment]
I think this should be moved to Scripts as it is an engine specific issue.

**Comment by plata** [comment]
Superseded by PhoenicisOrg/Scripts#369
