### ISSUE TITLE
Add a way to change the default list widget to the settings tab

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#850]
Currently the default list widget at startup is the `IconsListWidget`. It would be nice if the user can change this inside the "Settings" tab.

**Comment by madoar** [comment]
Hmm, I think this is a fundamental design decision. 
I'm someone who likes it, when an application "resets" after the application has been restarted.
Other people, like you describe, may like it more if the application "remembers" how it looked like before it has been restarted.
Not sure which way is best.

**Comment by plata** [comment]
If a user changes the list type, she probably wants to keep it. Therefore it would be annoying (for me) if she would have to go to settings first to store this.
