### ISSUE TITLE
decide on localization service

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#898]
Decide where to store the localization files in a way that people can provide localization files in an easy way
  * [Transifex](https://docs.transifex.com/formats/java-properties) (nice but expensive)
  * [Weblate](https://weblate.org/en/) (free, integrates with git/GitHub)
  * [Pootle](http://pootle.translatehouse.org/)
  * Rosetta (as in #4; often slow and buggy)

**Comment by plata** [comment]
@qparis can we take a decision here?

**Comment by plata** [comment]
I would like to try [Crowdin](https://github.com/marketplace/crowdin).

**Comment by plata** [comment]
Crowdin requires to fill a request: https://crowdin.com/page/open-source-project-setup-request. I don't think it's a problem but I would prefer if @qparis could check as well.

**Comment by plata** [comment]
@qparis now that the translation files for the scripts are updated automatically by Travis as soon as new strings are committed, I would really like to set up Crowdin and get started with the translations.
Please check if it is ok to fill the request (see above), so I can continue here. It shouldn't take more than a few minutes.

**Comment by qparis** [comment]
The giant advantage of Rosetta is the community: there are a lot of people that translates strings for ‘random’ open source projects.


Does crowdin has this kind of community?

Anyway, I think we should go ahead and try, it is the best way to know if the solution suits our need

**Comment by plata** [comment]
I'm not sure about the community at crowdin. However, from my personal experience I'd say that people rather translate strings for software they want to use in their own language. So the way would be from Phoenicis to Crowdin instead of from Rosetta to Phoenicis.
Anyways, we will have the translated files in the repository so it shouldn't be difficult to switch the localization service later on if Crowdin doesn't fit our needs.

**Comment by plata** [comment]
@madoar @qparis please check if you can access https://crowdin.com/project/phoenicis and https://crowdin.com/project/phoenicis-scripts. I'm not sure if I must invite you. If so, I need your email or crowdin name.

**Comment by madoar** [comment]
I can access the pages. 
Is there something I need to be able to do?

**Comment by plata** [comment]
You should at least be "Translator" and be able to translate strings. If you want, you can be admin as well.

**Comment by madoar** [comment]
I seem to be able to provide translations, I don't think I need to be an admin on Crowdin

**Comment by plata** [comment]
ok

**Comment by madoar** [comment]
How exactly does the translation process work with Crowdin?
I mean it seems to have github integration, so does it automatically create a new PR when a user submits a new translation?

**Comment by plata** [comment]
Exactly. E.g. #1181 has been created by crowdin after I've updated the German translations.

**Comment by madoar** [comment]
Hmm, does it always use your github name?

**Comment by plata** [comment]
I guess yes because I've created the crowdin project. I've already asked their support if it's possible to change that.

**Comment by plata** [comment]
The support told me that we should create a bot user account to achieve this.

**Comment by madoar** [comment]
Did they tell you a reason why they don't provide a bot themselves? (Just asking)

**Comment by plata** [comment]
> The main reason is that you connect your GitHub account with sufficient read/write permissions to Crowdin. Thus currently all PRs are going from manager's name who has established the integration.
> 
> Anyway, developers say it should be quite possible for us to submit PRs from Crowdin Bot name. They just never thought it might be a requested functionality. :)

**Comment by plata** [comment]
As Crowdin seems to be working quite nicely, I close this.
