### ISSUE TITLE
Add a new ObservableList implementation that provides an ObjectProperty for the first and last element of the list

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#926]
It would be quite useful to implement a new ObservableList class, that provides an ObjectProperty for the first and the last element of the list. 
These properties need to automatically update themselves and need to inform all their listeners when a change to the first or last element of the list occurs.

This class is quite helpful for #849 and similar issues

**Comment by madoar** [comment]
A few more information about this:
This list could be helpful for managing our themes, because we can't ensure that a theme contains all required files, therefore we need a fallback mechanism, which automatically selects the next source in the chain, that contains the required file. 
I'm not sure if this is absolutely necessary. I guess there are some alternative approaches we could take that are easier.

**Comment by plata** [comment]
Don't we have such a fallback mechanism already? I.e. our fallback should be the default theme.

**Comment by madoar** [comment]
I think you're right.
