### ISSUE TITLE
Probably information about installed app is in wrong place.

### ISSUE THREAD

**Issue by pyroxar** [PhoenicisOrg/POL-POM-5#931]
I'm not sure information about installed app  is in the right place.
In my opinion it is too high.
![zrzut ekranu z 2017-06-27 22-49-09](https://user-images.githubusercontent.com/23406555/27631032-8d1d8ed0-5bf7-11e7-99bf-8b8ce24e4cc5.png)
![zrzut ekranu z 2017-06-27 22-49-092](https://user-images.githubusercontent.com/23406555/27631163-e5249786-5bf7-11e7-851e-ed45d32b2727.png)

**Comment by madoar** [comment]
Do you mean only the header row (e.g. Notepad++ and the close button) are too high, or everything in the details view?
Can you maybe add a screenshot showing how you would like it to look?

**Comment by pyroxar** [comment]
imo this should be something like this:
![opo](https://user-images.githubusercontent.com/23406555/27645195-d02c974c-5c25-11e7-91a7-6ed99fce88d3.png)

**Comment by madoar** [comment]
The current idea about the details view (which is the application information for the library tab) is to add it separately from the main content of the tab.
Therefore we don't want to include the application information inside the "My applications" tab inside the library, but next to it as a separate element.

**Comment by madoar** [comment]
Do you think a border around the details tab (e.g. the application information for the library tab) would make this more clear?

**Comment by plata** [comment]
It might make sense to move the details into the tab content like @pyroxar suggests. If you install an application, switch to "My application" while the wizard is open, click on a miniature and then switch back to the wizard, you will have the details panel besides the wizard which doesn't make a lot of sense.

**Comment by madoar** [comment]
This might be useful, but if we want to do what you propose, we would need to add a custom implementation for the setting of the sidebar for the library tab. I'm not sure this is a good idea, because it would make it more complex for developers to understand.

**Comment by plata** [comment]
Maybe we should show the right panel inside the tab content everywhere.

**Comment by madoar** [comment]
I'm not sure I can follow you, what do you mean with `inside the tab content everywhere`?

**Comment by plata** [comment]
As you said, the right panel is currently shown **beside** the `TabPane`. Maybe we should show it **inside** the tab instead like @pyroxar suggests.

**Comment by madoar** [comment]
Yes, but not every function tab contains a `TabPane`, right?

**Comment by plata** [comment]
Ok, but I think you got the point. If not in the `TabPane` then maybe in the miniature view or something like that.

**Comment by madoar** [comment]
I got your point, but my argument still stands: 

> This might be useful, but if we want to do what you propose, we would need to add a custom implementation to set the sidebar for the library tab (and engine tab). I'm not sure this is a good idea, because it would make it more complex for developers to understand.

**Comment by plata** [comment]
That's true. But I don't think we should use the developer perspective to argue about the user experience.

**Comment by madoar** [comment]
I think, that a border around the details view could be enough to make it apparent to the user, that the details view is not part of the center view.

**Comment by plata** [comment]
That's true. But still the question: Does it make sense that it is like this (especially in the case of the wizard I described above)?

**Comment by plata** [comment]
@madoar I would suggest to close this as "won't fix". I agree with @pyroxar that the layout is a bit weird. However, I would not want to break the general concept of sidebar - content -details. Also I'm not sure that it's a good idea to show the install wizard in a tab in "Library".
I propose to structure it similar to Steam, i.e. add an "Installations" tab which collects all running installations. We could then also show the progress for engine installations there. If you currently install an engine and ten show the details of another one, you completely loose the install progress/if anything went wrong.
If we do it like this, we can remove the "My apps" tab completely which will avoid the whole confusion in the first place.

**Comment by madoar** [comment]
Let's go with your suggestion. 
Can you open a new issue?
