### ISSUE TITLE
implement JavaFxSettingsManager

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#950]
Currently, all settings (except repositories) are stored in one properties file and are managed by `SettingsManager`. However, some of the settings (like window size) only apply to JavaFX. Therefore, those should be extracted and handled separately. This is also required for #850 because the list type enum cannot be used in `SettingsManager` right now (circular dependency between phoenicis-javafx and phoenicis-settings).

**Comment by madoar** [comment]
In which format do you want to store the settings for the javafx application?
Do you want to store them in a properties file or in json?

**Comment by plata** [comment]
Didn't really think about it. I guess we can use properties as well.

**Comment by madoar** [comment]
Json is easier to use in my opinion, because we can simply annotate all fields/methods, that should be persisted in json. The saving and loading will then be done by jackson, without the need to do it ourselves.

**Comment by qparis** [comment]
Yes we can use properties

**Comment by qparis** [comment]
@madoar With json, you cannot inject properties when running POL, you must modify the file. I think it is not that hard to read and write into properties

**Comment by plata** [comment]
How do we specify the file name for the JavaFX settings? For the normal settings it's done in `PhoenicisGlobalConfiguration`. I think we cannot use the same approach otherwise we would have the `JavaFX` settings even e.g. in the CLI version.
