### ISSUE TITLE
add Wine 2.14

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#973]

**Comment by plata** [comment]
@qparis is it possible to automate this in a way that we always have the latest Wine version available? I think it's a bit problematic if this depends on the manual work of one person.

**Comment by madoar** [comment]
I've googled a little bit and found this github repository https://github.com/wine-mirror/wine/releases, which seems to be a mirror for the wine repository.
Can't we download the releases from there? As far as I understand the github api this seems to be possible: https://developer.github.com/v3/repos/releases/.

**Comment by qparis** [comment]
They should be automated. This is not normal

**Comment by plata** [comment]
Oh ok. Wasn't aware of that. I thought you had to do it manually because 2.14 wasn't available (and still is not).

**Comment by qparis** [comment]
It is a problem of disk space in the server. The build should arrive soon
