### ISSUE TITLE
Move the engine specific location path to the engine implementation in the scripts repository

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#984]
Currently the wineprefix folder location is set inside a configuration file in the POL 5 repository.
This is kind of bad, because this requires us to add the paths for all later engines to the POL 5 repository too. Therefore I suggest to split the path in two parts.

- the first part of the path `${application.user.root}/containers/` describes the root location, where all engines should be located. This path should be set from inside POL 5.
- the second part of the path, which is engine specific, i.e. for wine `wineprefix` should be set from inside the engines.

For more details, please take a look at #980

**Comment by plata** [comment]
I've just looked into the scripts. The `wineprefix` property is used in several places. So we cannot easily remove it. I'm thinking if it makes sense to have a `wineprefix` folder inside containers at all. How about having all containers in one directory and adding the type to `phoenicis.cfg`?

**Comment by madoar** [comment]
Hmm, I don't know. I think it is useful to distinguish different container types by using directories, but I could also imagine using a config file (i.e. `phoenicis.cfg`) for this.
@qparis what do you think?
