### ISSUE TITLE
${user.home} evaluated at build time

### ISSUE THREAD

**Issue by plata** [PhoenicisOrg/POL-POM-5#991]
### in logback.xml 
E.g. if you build a .deb and try to run it as a different user/on a different computer, the logback.xml contains a path to **your** .Phoenicis directory. Thus, logging will not work.

### in .properties
E.g. `application.user.root` points to an invalid path which causes multiple problems.

**Comment by madoar** [comment]
Hmm, I have no idea how to solve this. I would expect maven to use the environmental variable from the installed JVM...

**Comment by plata** [comment]
I have a solution already. Will create a PR in a minute.
