### ISSUE TITLE
Implement an update engine wizard for the containers

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/POL-POM-5#992]
Currently it is not possible to change the engine of an existing container.
Therefore we should implement a wizard for this this.
This wizard should be reachable by a button inside the container view. After clicking on this button a new tab or dialog should open which shows a list of existing engines. This list should look like the one located inside the "Engines" tab, where all already installed engines are marked. After selecting an engine inside the wizard a details view at the right side of the wizard should open, where the user finds a button through which he has the choice to update the engine of his container to the selected engine.

For more context about this see #974

**Comment by plata** [comment]
consider also #702

**Comment by plata** [comment]
Superseeded by #1024.
